### ISSUE TITLE
instant aegis armor crash

### ISSUE THREAD

**Issue by ChloeTax** [ChloeTax/Hexxytest#19]
if the armor made by instant aegis armor is put in your main inv, it crashes

```
Mind's Reflection
Numerical Reflection: 10
Numerical Reflection: 10
Nullary Reflection
Nullary Reflection
Instant_Aegis
```

```
[06:00:47] [Server thread/WARN]: Neruina caught an exception, see below for cause
java.lang.NullPointerException: Cannot invoke "net.minecraft.entity.EquipmentSlot.getType()" because "$$0" is null
    at net.minecraft.entity.player.PlayerEntity.getEquippedStack(PlayerEntity.java:1958) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.LivingEntity.handler$ggm000$fabrication$sendEquipmentBreakStatus(LivingEntity.java:55686) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.LivingEntity.sendEquipmentBreakStatus(LivingEntity.java) ~[minecraft-1.19.2.i0:0/:?]
    at net.beholderface.ephemera.items.ConjuredArmorItem.lambda$inventoryTick$0(ConjuredArmorItem.java:88) ~[ephemera-0.1.0.i0:0/:?]
    at net.minecraft.item.ItemStack.damage(ItemStack.java:368) ~[minecraft-1.19.2.i0:0/:?]
    at net.beholderface.ephemera.items.ConjuredArmorItem.inventoryTick(ConjuredArmorItem.java:87) ~[ephemera-0.1.0.i0:0/:?]
    at net.minecraft.item.ItemStack.inventoryTick(ItemStack.java:542) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.player.PlayerInventory.mixinextras$bridge$method_7917$68(PlayerInventory.java) ~[minecraft-1.19.2.i0:0/:?]
    at com.bawnorton.neruina.handler.TickHandler.safelyTickItemStack(TickHandler.java:68) ~[neruina-2.1.0.i0:0/:?]
    at net.minecraft.entity.player.PlayerInventory.wrapOperation$eik000$neruina$catchTickingItemStack$notTheCauseOfTickLag(PlayerInventory.java:4184) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.player.PlayerInventory.updateItems(PlayerInventory.java:255) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.player.PlayerEntity.tickMovement(PlayerEntity.java:567) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2385) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:284) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:487) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.network.ServerPlayNetworkHandler.mixinextras$bridge$method_14226$242(ServerPlayNetworkHandler.java) ~[minecraft-1.19.2.i0:0/:?]
    at com.bawnorton.neruina.handler.TickHandler.safelyTickPlayer(TickHandler.java:122) ~[neruina-2.1.0.i0:0/:?]
    at net.minecraft.server.network.ServerPlayNetworkHandler.wrapOperation$eif000$neruina$catchTickingPlayer$notTheCauseOfTickLag(ServerPlayNetworkHandler.java:9515) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:268) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.network.ClientConnection.tick(ClientConnection.java:248) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:183) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:886) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:289) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:819) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.MinecraftServer.handler$fjm000$carpet$modifiedRunLoop(MinecraftServer.java:19885) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644) ~[minecraft-1.19.2.i0:0/:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[minecraft-1.19.2.i0:0/:?]
    at java.lang.Thread.run(Thread.java:840) [?:?]
```

**Comment by ChloeTax** [comment]
(hasn't been tested with only ephemera and dependencies yet)

**Comment by ChloeTax** [comment]
fixed in one of the oneironaut updates and i forgot to close this, oops
